import { randomUUID } from "node:crypto";
import type { AssetKind, ClipCandidate, ProcessingSettings, ProjectRecord, ProjectStatus, TranscriptSegment } from "../shared/types.js";
import { one, query } from "./pool.js";

type ProjectRow = { id: string; title: string; status: ProjectStatus; original_filename: string; mime_type: string; bytes: string; duration_ms: number | null; width: number | null; height: number | null; settings: ProcessingSettings; error_code: string | null; error_message: string | null; created_at: Date; updated_at: Date; job_stage: string | null; job_progress: number | null; };
// Pulls in the latest processing_jobs row (stage + progress) for this project, via
// the existing processing_jobs(project_id, created_at DESC) index, so the API and
// frontend can show the real pipeline stage instead of a guessed/hardcoded number.
const PROJECT_WITH_JOB_SQL = `
  SELECT p.*, j.stage AS job_stage, j.progress AS job_progress
  FROM projects p
  LEFT JOIN LATERAL (
    SELECT stage, progress FROM processing_jobs
    WHERE project_id = p.id
    ORDER BY created_at DESC
    LIMIT 1
  ) j ON true
`;
function project(row: ProjectRow): ProjectRecord { return { id: row.id, title: row.title, status: row.status, originalFilename: row.original_filename, mimeType: row.mime_type, bytes: Number(row.bytes), durationMs: row.duration_ms, width: row.width, height: row.height, settings: row.settings, errorCode: row.error_code, errorMessage: row.error_message, createdAt: row.created_at.toISOString(), updatedAt: row.updated_at.toISOString(), jobStage: row.job_stage, jobProgress: row.job_progress }; }
export async function createProject(input: { title: string; filename: string; mimeType: string; settings: ProcessingSettings }): Promise<ProjectRecord> { const row = await one<ProjectRow>("INSERT INTO projects(id,title,original_filename,mime_type,settings,status) VALUES($1,$2,$3,$4,$5,'draft') RETURNING *, NULL::text AS job_stage, NULL::int AS job_progress", [randomUUID(), input.title, input.filename, input.mimeType, input.settings]); if (!row) throw new Error("Project creation failed"); return project(row); }
export async function getProject(id: string): Promise<ProjectRecord | null> { const row = await one<ProjectRow>(`${PROJECT_WITH_JOB_SQL} WHERE p.id=$1`, [id]); return row ? project(row) : null; }
export async function listProjects(): Promise<ProjectRecord[]> { return (await query<ProjectRow>(`${PROJECT_WITH_JOB_SQL} ORDER BY p.updated_at DESC LIMIT 100`)).map(project); }
export async function setProjectStatus(id: string, status: ProjectStatus, details: { durationMs?: number; width?: number; height?: number; bytes?: number; errorCode?: string | null; errorMessage?: string | null } = {}): Promise<void> { await query("UPDATE projects SET status=$2::project_status,duration_ms=COALESCE($3,duration_ms),width=COALESCE($4,width),height=COALESCE($5,height),bytes=COALESCE($6,bytes),error_code=$7,error_message=$8,updated_at=now() WHERE id=$1", [id, status, details.durationMs ?? null, details.width ?? null, details.height ?? null, details.bytes ?? null, details.errorCode ?? null, details.errorMessage ?? null]); }
export async function updateSettings(id: string, settings: ProcessingSettings): Promise<void> { await query("UPDATE projects SET settings=$2,updated_at=now() WHERE id=$1", [id, settings]); }
export async function createAsset(projectId: string, kind: AssetKind, storageKey: string, mimeType: string, bytes = 0, metadata: Record<string, unknown> = {}, expiresAt?: Date): Promise<string> { const id = randomUUID(); const row = await one<{ id: string }>("INSERT INTO media_assets(id,project_id,kind,storage_key,mime_type,bytes,metadata,expires_at) VALUES($1,$2,$3::asset_kind,$4,$5,$6,$7,$8) ON CONFLICT(storage_key) DO UPDATE SET bytes=EXCLUDED.bytes,metadata=EXCLUDED.metadata,expires_at=EXCLUDED.expires_at RETURNING id", [id, projectId, kind, storageKey, mimeType, bytes, metadata, expiresAt ?? null]); if (!row) throw new Error("Asset write failed"); return row.id; }
export type AssetRow = { id: string; project_id: string; kind: AssetKind; storage_key: string; mime_type: string; bytes: string; metadata: Record<string, unknown>; expires_at: Date | null; };
export async function getAsset(id: string): Promise<AssetRow | null> { return one<AssetRow>("SELECT * FROM media_assets WHERE id=$1 AND (expires_at IS NULL OR expires_at > now())", [id]); }
export async function findAsset(projectId: string, kind: AssetKind): Promise<AssetRow | null> { return one<AssetRow>("SELECT * FROM media_assets WHERE project_id=$1 AND kind=$2::asset_kind ORDER BY created_at DESC LIMIT 1", [projectId, kind]); }
export async function createJob(projectId: string, type: "analyze" | "export" | "cleanup"): Promise<string> { const id = randomUUID(); await query("INSERT INTO processing_jobs(id,project_id,type,status,stage) VALUES($1,$2,$3,'queued','queued')", [id, projectId, type]); return id; }
export async function updateJob(id: string, status: "queued" | "running" | "succeeded" | "retryable_failed" | "terminal_failed" | "canceled", stage: string, progress: number, error?: { code: string; message: string }): Promise<void> { await query("UPDATE processing_jobs SET status=$2::job_status,stage=$3,progress=$4,attempt=CASE WHEN $2::text='running' THEN attempt+1 ELSE attempt END,error_code=$5,error_message=$6,started_at=CASE WHEN $2::text='running' THEN COALESCE(started_at,now()) ELSE started_at END,finished_at=CASE WHEN $2::text IN ('succeeded','terminal_failed','canceled') THEN now() ELSE NULL END,updated_at=now() WHERE id=$1", [id, status, stage, progress, error?.code ?? null, error?.message ?? null]); }
export async function addStep(jobId: string, stage: string, status: "queued" | "running" | "succeeded" | "retryable_failed" | "terminal_failed" | "canceled", detail: Record<string, unknown> = {}): Promise<void> { await query("INSERT INTO job_steps(id,job_id,stage,status,detail,finished_at) VALUES($1,$2,$3,$4::job_status,$5,CASE WHEN $4::text IN ('succeeded','terminal_failed','canceled') THEN now() ELSE NULL END)", [randomUUID(), jobId, stage, status, JSON.stringify(detail)]); }
export async function replaceTranscript(projectId: string, segments: TranscriptSegment[]): Promise<void> { await query("DELETE FROM transcript_segments WHERE project_id=$1", [projectId]); for (const segment of segments) await query("INSERT INTO transcript_segments(id,project_id,start_ms,end_ms,speaker,text,words,confidence) VALUES($1,$2,$3,$4,$5,$6,$7,$8)", [randomUUID(), projectId, segment.startMs, segment.endMs, segment.speaker ?? null, segment.text, JSON.stringify(segment.words), segment.confidence ?? null]); }
type SegmentRow = { start_ms: number; end_ms: number; speaker: string | null; text: string; words: TranscriptSegment["words"]; confidence: number | null; };
export async function getTranscript(projectId: string): Promise<TranscriptSegment[]> { return (await query<SegmentRow>("SELECT start_ms,end_ms,speaker,text,words,confidence FROM transcript_segments WHERE project_id=$1 ORDER BY start_ms", [projectId])).map((row) => ({ startMs: row.start_ms, endMs: row.end_ms, speaker: row.speaker ?? undefined, text: row.text, words: row.words, confidence: row.confidence ?? undefined })); }
export async function replaceClips(projectId: string, clips: ClipCandidate[], aspectRatio: string, captionStyle: string): Promise<string[]> { await query("DELETE FROM clips WHERE project_id=$1", [projectId]); const ids: string[] = []; for (const [index, clip] of clips.entries()) { const id = randomUUID(); ids.push(id); await query("INSERT INTO clips(id,project_id,rank,start_ms,end_ms,score,score_breakdown,title,hook,transcript_excerpt,aspect_ratio,caption_style) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)", [id, projectId, index + 1, clip.startMs, clip.endMs, clip.score, JSON.stringify(clip.scoreBreakdown), clip.title, clip.hook ?? null, clip.transcriptExcerpt, aspectRatio, captionStyle]); } return ids; }
export type ClipRow = { id: string; project_id: string; rank: number; start_ms: number; end_ms: number; score: number; score_breakdown: Record<string, number>; title: string; hook: string | null; transcript_excerpt: string; crop_mode: string; caption_style: string; aspect_ratio: string; preview_asset_id: string | null; captions_asset_id: string | null; };
export async function listClips(projectId: string): Promise<ClipRow[]> { return query<ClipRow>("SELECT * FROM clips WHERE project_id=$1 ORDER BY rank", [projectId]); }
export async function getClip(id: string): Promise<ClipRow | null> { return one<ClipRow>("SELECT * FROM clips WHERE id=$1", [id]); }
export async function attachClipAssets(clipId: string, previewAssetId: string, captionsAssetId: string): Promise<void> { await query("UPDATE clips SET preview_asset_id=$2,captions_asset_id=$3,updated_at=now() WHERE id=$1", [clipId, previewAssetId, captionsAssetId]); }
export async function updateClip(id: string, patch: { title?: string; hook?: string | null; captionStyle?: string; aspectRatio?: string; cropMode?: string; startMs?: number; endMs?: number }): Promise<void> { await query("UPDATE clips SET title=COALESCE($2,title),hook=COALESCE($3,hook),caption_style=COALESCE($4,caption_style),aspect_ratio=COALESCE($5,aspect_ratio),crop_mode=COALESCE($6,crop_mode),start_ms=COALESCE($7,start_ms),end_ms=COALESCE($8,end_ms),updated_at=now() WHERE id=$1", [id, patch.title ?? null, patch.hook ?? null, patch.captionStyle ?? null, patch.aspectRatio ?? null, patch.cropMode ?? null, patch.startMs ?? null, patch.endMs ?? null]); }
export async function createExport(clipId: string, preset: string): Promise<string> { const id = randomUUID(); await query("INSERT INTO exports(id,clip_id,status,preset) VALUES($1,$2,'queued'::job_status,$3)", [id, clipId, preset]); return id; }
export async function setExport(id: string, status: "queued" | "running" | "succeeded" | "retryable_failed" | "terminal_failed" | "canceled", assetId?: string, errorMessage?: string): Promise<void> { await query("UPDATE exports SET status=$2::job_status,asset_id=COALESCE($3::uuid,asset_id),error_message=$4,updated_at=now() WHERE id=$1", [id, status, assetId ?? null, errorMessage ?? null]); }
export async function getExport(id: string): Promise<{ id: string; clip_id: string; status: string; preset: string; asset_id: string | null; error_message: string | null } | null> { return one("SELECT id,clip_id,status,preset,asset_id,error_message FROM exports WHERE id=$1", [id]); }
